swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /user/:
    get:
      tags:
      - user
      description: get all Users
      operationId: UserController.GetAll
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.User'
    post:
      tags:
      - user
      description: create users
      operationId: UserController.CreateUser
      parameters:
      - in: body
        name: body
        description: body for user content
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: '{int} models.User.Id'
        "403":
          description: body is empty
  /user/{uid}:
    get:
      tags:
      - user
      description: get user by uid
      operationId: UserController.Get
      parameters:
      - in: path
        name: uid
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.User'
        "403":
          description: :uid is empty
definitions:
  models.Post:
    title: Post
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Tags:
        type: array
        items:
          $ref: '#/definitions/models.Tag'
      Title:
        type: string
      User:
        $ref: '#/definitions/models.User'
  models.Profile:
    title: Profile
    type: object
    properties:
      Age:
        type: integer
        format: int32
      Id:
        type: integer
        format: int64
      User:
        $ref: '#/definitions/models.User'
  models.Tag:
    title: Tag
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Name:
        type: string
      Posts:
        type: array
        items:
          $ref: '#/definitions/models.Post'
  models.User:
    title: User
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Name:
        type: string
      Post:
        type: array
        items:
          $ref: '#/definitions/models.Post'
      Profile:
        $ref: '#/definitions/models.Profile'
tags:
- name: user
  description: |
    Operations about Users
